---
abstract: 'Generic complex number library.'
author:
  - 'Daniel Șuteu <trizen@protonmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-GComplex
provides:
  Math::GComplex:
    file: lib/Math/GComplex.pm
    version: '0.04'
recommends:
  Math::AnyNum: '0.20'
requires:
  perl: '5.010'
resources:
  bugtracker: https://github.com/trizen/Math-GComplex/issues
  homepage: https://github.com/trizen/Math-GComplex
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/trizen/Math-GComplex
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
